import aiohttp
from enums.categories import CategoriesEnum
from pydantic import BaseModel
from services.ai.openai_service import OpenAIService


class CategoriesService:
    enum = CategoriesEnum
    category_keys: list[str] = list(map(lambda x: x.name, enum))

    def __init__(self, openai: OpenAIService):
        self.openai = openai
        self.select_categories_system_prompt = '''
There are categories to choose from:

reality - believable, realistic scenes, like photos. Everyday shots, portraits, lifestyle;

worlds - antonym of reality. Everything that is not real, invented worlds, scenes, celebrities, fantasy, science fiction,
fictional spaces, heroes, fairy-tale scenes;

aesthetics - everything about visual style, beauty, mood, art, and fashion. Concept art, stylization,
mood, design, and art photography;
            
You must choose which categories the image generated by the neural network belongs to'''

    async def generate_categories_for_image(self, image_url: str, session: aiohttp.ClientSession) -> list[str]:
        class GPTSchema(BaseModel):
            categories: list[CategoriesEnum] = []

        res = await self.openai.send_images_get_schema(
            schema=GPTSchema,
            photo_urls=[image_url],
            messages=[{
                'role': 'system',
                'content': self.select_categories_system_prompt
            }],
            model='gpt-5-mini',
            session=session,
            has_tries=1
        )
        keys = list(map(lambda x: str(x.name), res.categories))
        print(f'{keys=}')
        return keys