"""update

Revision ID: 266366755740
Revises: ec6aefa202b5
Create Date: 2025-10-22 00:08:57.169785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266366755740'
down_revision: Union[str, Sequence[str], None] = 'ec6aefa202b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('generated_images_categories_image_id_fkey'), 'generated_images_categories', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images_categories', 'generated_images', ['image_id'], ['id'])
    op.add_column('models', sa.Column('status', sa.String(), server_default='ready', nullable=False))
    op.add_column('payments', sa.Column('type', sa.String(), server_default='package', nullable=False))
    op.alter_column('payments', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('users_current_avatar_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'avatars', ['current_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_current_avatar_id_fkey'), 'users', 'avatars', ['current_avatar_id'], ['id'], ondelete='SET NULL')
    op.alter_column('payments', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'type')
    op.drop_column('models', 'status')
    op.drop_constraint(None, 'generated_images_categories', type_='foreignkey')
    op.create_foreign_key(op.f('generated_images_categories_image_id_fkey'), 'generated_images_categories', 'generated_images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
