"""add generated_images.is_public

Revision ID: 3faddab6d5f5
Revises: fa8f78eea1c9
Create Date: 2025-10-20 20:42:17.136220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faddab6d5f5'
down_revision: Union[str, Sequence[str], None] = 'fa8f78eea1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('is_private', sa.Boolean(), server_default='False', nullable=False))
    op.drop_constraint(op.f('users_current_avatar_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'avatars', ['current_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_current_avatar_id_fkey'), 'users', 'avatars', ['current_avatar_id'], ['id'], ondelete='SET NULL')
    op.drop_column('generated_images', 'is_private')
    # ### end Alembic commands ###
