"""add users.can_create_avatar

Revision ID: 618abe77699f
Revises: 6ad2bf4f7461
Create Date: 2025-11-03 23:26:54.379383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618abe77699f'
down_revision: Union[str, Sequence[str], None] = '6ad2bf4f7461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_create_avatar', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_avatar')
    # ### end Alembic commands ###
