"""update generated images

Revision ID: 6ad2bf4f7461
Revises: 415174f7cdf4
Create Date: 2025-10-23 23:38:07.640295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad2bf4f7461'
down_revision: Union[str, Sequence[str], None] = '415174f7cdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('ratio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'ratio')
    # ### end Alembic commands ###
