"""add categories

Revision ID: 86958e51a939
Revises: 593057fd45dc
Create Date: 2025-10-21 17:32:29.939892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86958e51a939'
down_revision: Union[str, Sequence[str], None] = '593057fd45dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('generated_images_categories',
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.ForeignKeyConstraint(['image_id'], ['generated_images.id'], ),
    sa.PrimaryKeyConstraint('category_key', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_images_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
