"""update avatars

Revision ID: ec6aefa202b5
Revises: 86958e51a939
Create Date: 2025-10-21 22:39:03.503091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec6aefa202b5'
down_revision: Union[str, Sequence[str], None] = '86958e51a939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fal_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('diffusers_url', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'avatars', 'users', ['user_id'], ['id'])
    op.drop_column('avatars', 'photos')
    op.drop_column('avatars', 'model')
    op.drop_column('avatars', 'level')
    op.add_column('generated_images', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'generated_images', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_column('generated_images', 'model_id')
    op.add_column('avatars', sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('avatars', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('photos', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'avatars', type_='foreignkey')
    op.drop_table('models')
    op.drop_table('fal_requests')
    # ### end Alembic commands ###
