"""update avatars, rm models

Revision ID: edc1a2792f40
Revises: 618abe77699f
Create Date: 2025-11-14 18:14:54.195079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc1a2792f40'
down_revision: Union[str, Sequence[str], None] = '618abe77699f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE models CASCADE')
    op.add_column('avatars', sa.Column('model_data', sa.String(), nullable=True))
    op.add_column('avatars', sa.Column('level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('avatars', sa.Column('status', sa.String(), server_default='ready', nullable=False))
    op.add_column('fal_requests', sa.Column('user_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'fal_requests', 'users', ['user_id'], ['id'])
    op.add_column('generated_images', sa.Column('avatar_id', sa.Integer(), nullable=False))
    # op.drop_constraint(op.f('generated_images_model_id_fkey'), 'generated_images', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images', 'avatars', ['avatar_id'], ['id'])
    op.drop_column('generated_images', 'model_id')
    op.add_column('users', sa.Column('can_create_avatar_level', sa.Integer(), nullable=True))
    op.drop_column('users', 'can_create_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('can_create_avatar', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False,
                            nullable=False))
    op.drop_column('users', 'can_create_avatar_level')
    op.add_column('generated_images', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.create_foreign_key(op.f('generated_images_model_id_fkey'), 'generated_images', 'models', ['model_id'], ['id'])
    op.drop_column('generated_images', 'avatar_id')
    op.drop_constraint(None, 'fal_requests', type_='foreignkey')
    op.drop_column('fal_requests', 'user_id')
    op.drop_column('avatars', 'status')
    op.drop_column('avatars', 'level')
    op.drop_column('avatars', 'model_data')
    op.create_table('models',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('avatar_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('photos', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
                    sa.Column('diffusers_url', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
                    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ready'::character varying"),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], name=op.f('models_avatar_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('models_pkey'))
                    )
    # ### end Alembic commands ###
