"""add users.avatar_url

Revision ID: ef4fe1f151ba
Revises: a03712b6e57e
Create Date: 2025-10-13 01:23:41.738569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4fe1f151ba'
down_revision: Union[str, Sequence[str], None] = 'a03712b6e57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'generated_images', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    # ### end Alembic commands ###
