"""add promocodes

Revision ID: f3bf00c2a95d
Revises: b6a10142476c
Create Date: 2026-01-14 20:39:20.929372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bf00c2a95d'
down_revision: Union[str, Sequence[str], None] = 'b6a10142476c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sale_percentage', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('used_promocodes',
    sa.Column('promocode_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['promocode_code'], ['promocodes.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('promocode_code', 'user_id')
    )
    op.drop_constraint(op.f('avatars_user_id_fkey'), 'avatars', type_='foreignkey')
    op.create_foreign_key(None, 'avatars', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('generated_images_user_id_fkey'), 'generated_images', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_current_avatar_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'avatars', ['current_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_current_avatar_id_fkey'), 'users', 'avatars', ['current_avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.create_foreign_key(op.f('generated_images_user_id_fkey'), 'generated_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'avatars', type_='foreignkey')
    op.create_foreign_key(op.f('avatars_user_id_fkey'), 'avatars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('used_promocodes')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
