"""add users.image_generations

Revision ID: fa8f78eea1c9
Revises: ef4fe1f151ba
Create Date: 2025-10-13 01:31:50.952066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8f78eea1c9'
down_revision: Union[str, Sequence[str], None] = 'ef4fe1f151ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_generations', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_generations')
    # ### end Alembic commands ###
